server:
  port: 5001

spring:
  application:
    name: account.query
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    # show-sql: true
    # hibernate:
    #  ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/bankAccount
    username: postgres
    password: techbankRootPassword
    # url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
    # username: root
    # password: techbankRootPassword
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"