services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    restart: always

  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://172.25.5.166:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes" 
    restart: always
    depends_on:
      - zookeeper

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    restart: always

  mongo-express:
    image: mongo-express:latest
    ports:
      - 27016:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_MONGODB_SERVER: "mongo"

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "techbankRootPassword"

  adminer:
    image: adminer:latest
    ports:
      - 3305:8080
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: "mysql"

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgres/data 
    environment:
      POSTGRES_PASSWORD: techbankRootPassword

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_data:/var/lib/pgadmin/data

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
    driver: local
  mysql_data:
    driver: local
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    external:
      name: techbankNet
